doctrine:
    dbal:
        dbname:               database
        host:                 localhost
        port:                 3306
        user:                 root
        password:             Aa123456
        driver:               pdo_mysql
        url:                  mysql://root:Aa123456@database:3306/symfony_docker?serverVersion=8.0
        path:                 '%kernel.project_dir%/var/data/data.sqlite'
        memory:               true
        unix_socket:          /tmp/mysql.sock
        charset:              UTF8
        logging:              '%kernel.debug%'
        server_version:       '5.7'
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
