doctrine:
    dbal:
        dbname:               db_blocek
        host:                 localhost
        port:                 3306
        user:                 blocek_manager
        password:             Bb123456*
        driver:               pdo_mysql
        url:                  '%env(DATABASE_URL)%'
        path:                 '%kernel.project_dir%/var/data/data.sqlite'
#        path:                 '%kernel.cache_dir%/default.db'
        memory:               true
        unix_socket:          /tmp/mysql.sock
        charset:              UTF8
        logging:              '%kernel.debug%'
        server_version:       'mariadb-10.3.28'
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
